key_params = {
    'Вид лампы': 'opt_view_lamp',
    'Волновое сопротивление': 'opt_wave_resist',
    'Вольтаж': 'opt_voltage',
    'Диаметр': 'opt_diameter',
    'Диаметр, мм': 'opt_diameter',
    'Диаметр 1': 'opt_diameter_1',
    'Диаметр 1, мм': 'opt_diameter_1',
    'Диаметр 2': 'opt_diameter_2',
    'Диаметр 2, мм': 'opt_diameter_2',
    'Длина': 'opt_length',
    # new
    'Длина, м': 'opt_length_m',
    'Длина, мм': 'opt_length_mm',
    # end new
    'Длина гирлянды': 'opt_length_garland',
    'Длина гирлянды, м': 'opt_length_garland',
    'Количество винтов или болтов': 'opt_number_bolts',
    'Количество выключателей': 'opt_number_switches',
    'Количество гнезд': 'opt_number_nests',
    'Количество жил': 'opt_number_lived',
    'Количество контактов': 'opt_number_contacts',
    'Количество мест': 'opt_number_seats',
    'Количество клавиш': 'opt_number_keys',
    'Количество модулей': 'opt_number_modules',
    'Количество полюсов': 'opt_number_poles',
    'Количество розеток': 'opt_number_outlets',
    'Количество светодиодов на гирлянде': 'opt_number_LEDs_garland',
    'Количество светодиодов на гирлянде, шт': 'opt_number_LEDs_garland',
    'Количество фаз': 'opt_number_phases',
    'Комплектация': 'opt_package',
    'Максимальное сечение': 'opt_max_section',
    'Максимальное сечение, мм²': 'opt_max_section',
    'Материал': 'opt_material',
    'Материал корпуса': 'opt_material_copruse',
    'Минимальное сечение': 'opt_min_section',
    'Минимальное сечение, мм²': 'opt_min_section',
    'Модем': 'opt_modem',
    'Мощность': 'opt_power',
    # new
    'Мощность, Вт': 'opt_power_wt',
    'Мощность, квт': 'opt_power_kvt',
    'Мощность, кВА': 'opt_power_kva',
    # end new
    'Назначение': 'opt_destination',
    'Наличие заземления': 'opt_grounding',
    'Наличие светового индикатора': 'opt_light_indicator',
    'Напряжение': 'opt_tension',
    'Напряжение, В': 'opt_tension',
    'Напряжение катушек управления': 'opt_voltage_coil',
    'Напряжение катушек управления, В': 'opt_voltage_coil',
    'Номинальный первичный ток трансформатора': 'opt_rated_current_transformer',
    'Номинальный первичный ток трансформатора, A': 'opt_rated_current_transformer',
    'Номинальный ток': 'opt_rated_current',
    'Номинальный ток, A': 'opt_rated_current',
    'Номинальный ток Ie': 'opt_rated_current_Ie',
    'Номинальный ток Ie, A': 'opt_rated_current_Ie',
    'Номинальный ток in': 'opt_rated_current_in',
    'Номинальный ток in, A': 'opt_rated_current_in',
    'Номинальный ток контактов I': 'opt_rated_current_I',
    'Номинальный ток контактов I, A': 'opt_rated_current_I',
    'Номинальный ток расцепителя In': 'opt_rated_current_breaker',
    'Номинальный ток расцепителя In, A': 'opt_rated_current_breaker',
    'Особенности': 'opt_features',
    'Отключающая способность': 'opt_cutoff',
    'Отключающая способность, kA': 'opt_cutoff',
    'Отключающий ток IDn': 'opt_cutoff_IDn',
    'Отключающий ток IDn, mA': 'opt_cutoff_IDn',
    'Полюсность': 'opt_polarity',
    'Предельная отключающая способность Icu': 'opt_breaking_limit',
    'Предельная отключающая способность Icu, kA': 'opt_breaking_limit',
    'Прозрачность колбы лампы': 'opt_bulb_transparency',
    'Световой поток лампы': 'opt_light_flux',
    'Световой поток лампы, лм': 'opt_light_flux',
    'Свойства': 'opt_properties',
    'Силовые контакты': 'opt_power_contacts',
    'Степень защиты': 'opt_degree_protect',
    'Тип': 'opt_type',
    'Тип (колодки)': 'opt_type_pads',
    'Тип СИЗ': 'opt_type_PPE',
    'Тип аксессуаров для труб': 'opt_type_accessories_pipes',
    'Тип выключателя': 'opt_type_switch',
    'Тип гирлядн': 'opt_type_garlands',
    'Тип звонка': 'opt_type_call',
    'Тип изделия': 'opt_type_product',
    'Тип исполнения': 'opt_type_execution',
    'Тип лампы': 'opt_type_lamp',
    'Тип механизма': 'opt_type_mechanism',
    'Тип монтажа': 'opt_type_assembling',
    'Тип монтажа выключателя': 'opt_type_installation_switch',
    'Тип наконечника': 'opt_type_tip',
    'Тип отвертки': 'opt_type_screwdriver',
    'Тип прожектора': 'opt_type_spotlight',
    'Тип разъемы': 'opt_type_connectors',
    'Тип розетки': 'opt_type_outlet',
    'Тип светильника': 'opt_type_lantern',
    'Тип свечения': 'opt_type_glow',
    'Тип силового разъема': 'opt_type_power_connector',
    'Тип скоб металлических': 'opt_type_metal_braces',
    'Тип соединителя': 'opt_type_connector',
    'Тип установки': 'opt_type_installation',
    'Тип цоколя': 'opt_type_base',
    'Типоразмер лампы': 'opt_type_size_lamp',
    'Ток уставки теплового расцепителя': 'opt_current_thermal_trip',
    'Ток уставки теплового расцепителя, A': 'opt_current_thermal_trip',
    'Угол обзора': 'opt_view_angle',
    'Угол обзора, градусов': 'opt_view_angle',
    'Характеристика срабатывания': 'opt_trigger',
    'Цвет': 'opt_color',
    'Цветовая температура': 'opt_color_temperature',
    'Частота вращения': 'opt_rate_rotation',
    'Частота вращения, об/мин': 'opt_rate_rotation',
    'Ширина': 'opt_width',
    'Ширина, мм': 'opt_width',
    'Под какой тип ламп': 'opt_kind_lamp',
    'Под какой тип лампы': 'opt_kind_lamp',
    'Сечения': 'opt_section',
    'Сечение': 'opt_section',
    'Сечение, мм²': 'opt_section',
    'Сечения, мм²': 'opt_section',
    # new
    'Производитель': 'opt_fabricator',
    'Серия': 'opt_series',
    'Выбор типа кабеля': 'opt_cable_type',
}
